### ISSUE TITLE
Remove Breaks after every checkbox

### ISSUE THREAD

**Issue by FaiqH** [mikhail-tsennykh/MvcCheckBoxList#14]
Is there a way to remove the breaks after every checkbox?

**Comment by mikhail-tsennykh** [comment]
If you refer to `&nbsp;` symbol auto-inserted on horizontal lists, it's hardcoded and cannot be removed at the moment (for horizontal lists).

Source code:
https://github.com/mikhail-tsennykh/MvcCheckBoxList/blob/master/src/MvcCheckBoxList/ListBuilder.cs#L251
