### ISSUE TITLE
Website is offline

### ISSUE THREAD

**Issue by jorrit** [mikhail-tsennykh/MvcCheckBoxList#18]
The site http://mvccbl.com/ seems offline and as such the examples link doesn't work. Is it possible to publish the examples on a different site?

**Comment by mikhail-tsennykh** [comment]
Sure, it's live on GitHub pages: https://mikhail-tsennykh.github.io/MvcCheckBoxList/

**Comment by jorrit** [comment]
Thanks! The only remaining place is the nuspec file. Could you update that one as well?

**Comment by mikhail-tsennykh** [comment]
Np! good catch, updated .nuspec.

**Comment by jorrit** [comment]
You're the best!
